# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 392)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_connect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_connect.setGeometry(QtCore.QRect(430, 40, 111, 23))
        self.btn_connect.setObjectName("btn_connect")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 110, 101, 16))
        self.label.setObjectName("label")
        self.txt_history = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_history.setGeometry(QtCore.QRect(160, 90, 381, 61))
        self.txt_history.setObjectName("txt_history")
        self.txt_chat = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_chat.setGeometry(QtCore.QRect(160, 210, 381, 61))
        self.txt_chat.setObjectName("txt_chat")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 230, 91, 16))
        self.label_2.setObjectName("label_2")
        self.txt_send = QtWidgets.QPushButton(self.centralwidget)
        self.txt_send.setGeometry(QtCore.QRect(270, 290, 75, 23))
        self.txt_send.setObjectName("txt_send")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 590, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_connect.setText(_translate("MainWindow", "kết nối tới server"))
        self.label.setText(_translate("MainWindow", "Nhật ký hoạt động"))
        self.label_2.setText(_translate("MainWindow", "Nhập tin nhắn"))
        self.txt_send.setText(_translate("MainWindow", "Gửi tin nhắn"))
        self.label_3.setText(_translate("MainWindow", "Client"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
