# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_FLATFORM_PLUGIN_PATH'] = "../playforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(557, 357)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 120, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 200, 51, 16))
        self.label_2.setObjectName("label_2")
        self.btnSig = QtWidgets.QPushButton(self.centralwidget)
        self.btnSig.setGeometry(QtCore.QRect(150, 280, 56, 17))
        self.btnSig.setObjectName("btnSig")
        self.btnVerify = QtWidgets.QPushButton(self.centralwidget)
        self.btnVerify.setGeometry(QtCore.QRect(360, 280, 56, 17))
        self.btnVerify.setObjectName("btnVerify")
        self.btnGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerate.setGeometry(QtCore.QRect(380, 50, 91, 17))
        self.btnGenerate.setObjectName("btnGenerate")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 20, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txtinfo = QtWidgets.QTextEdit(self.centralwidget)
        self.txtinfo.setGeometry(QtCore.QRect(130, 90, 311, 64))
        self.txtinfo.setObjectName("txtinfo")
        self.txtSig = QtWidgets.QTextEdit(self.centralwidget)
        self.txtSig.setGeometry(QtCore.QRect(130, 180, 311, 64))
        self.txtSig.setObjectName("txtSig")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 557, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Infomation"))
        self.label_2.setText(_translate("MainWindow", "Signature"))
        self.btnSig.setText(_translate("MainWindow", "Sigature"))
        self.btnVerify.setText(_translate("MainWindow", "Verify"))
        self.btnGenerate.setText(_translate("MainWindow", "Generate Keys"))
        self.label_3.setText(_translate("MainWindow", "ECC Cipher"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
